#!/usr/bin/python

def test_ok():
    pass

def test_not_ok():
    raise Exception('Intentionally failed')
